package main

import (
	"fmt"

	"github.com/slzatz/vimango/vim"
)

func main() {
	vim.Init(0)

	vim.SetMessageCallback()
	buf0 := vim.BufferOpen("testfile.txt", 1, 0)
	fmt.Printf("buffer pointer: %p -> %T\n", buf0, buf0)

	i := vim.BufferGetId(buf0)
	fmt.Printf("Opened buffer id = %d\n", i)

	n := vim.BufferGetLineCount(buf0)
	fmt.Printf("Line Count = %d\n", n)

	ss := vim.BufferLinesS(buf0)
	fmt.Printf("%v\n", ss)

	m := vim.GetMode()
	fmt.Printf("NORMAL Mode = %d %X\n", m, m)
	vim.Input("i")
	m = vim.GetMode()
	fmt.Printf("INSERT Mode = %d\n", m)
	vim.Key("<esc>")
	vim.Input("gg0v8l")
	/*
		vim.Input("g")
		vim.Input("g")
		vim.Input("0")
		vim.Input("v")
		vim.Input("8")
		vim.Input("l")
	*/
	m = vim.GetMode()
	fmt.Printf("Visual Mode = %d\n", m)
	t := vim.VisualGetType()
	fmt.Printf("Visual type = %d\n", t)
	fmt.Printf("visual range = %v\n", vim.VisualGetRange())
	vim.Key("<esc>")
	vim.Input2("Vjj")
	/*
		vim.Input("V")
		vim.Input("j")
		vim.Input("j")
	*/
	m = vim.GetMode()
	fmt.Printf("Visual Line = %d\n", m)
	t = vim.VisualGetType()
	fmt.Printf("Visual type = %d\n", t)
	fmt.Printf("visual range = %v\n", vim.VisualGetRange())
	vim.Key("<esc>")
	vim.Input2("1gg02lj")
	/*
		vim.Input("1")
		vim.Input("g")
		vim.Input("g")
		vim.Input("0")
		vim.Input("2")
		vim.Input("l")
		vim.Input("j")
	*/
	pos := vim.CursorGetPosition()
	fmt.Printf("Position: line = %d, col = %d\n", pos[0], pos[1])
	fmt.Printf("cursor position = %v\n", pos)
	vim.Key("<c-v>")
	vim.Input2("lllj")
	m = vim.GetMode()
	fmt.Printf("Visual Block = %d\n", m)
	t = vim.VisualGetType()
	fmt.Printf("Visual type = %d\n", t)
	fmt.Printf("visual range = %v\n", vim.VisualGetRange())
	vim.Key("<esc>")
	vim.Input("r")
	m = vim.GetMode()
	fmt.Printf("REPLACE = %d %X\n", m, m)
	vim.Key("<esc>")
	vim.Input("/abc")
	m = vim.GetMode()
	fmt.Printf("SEARCH = %d %X\n", m, m)
	vim.Key("<esc>")
	vim.Input(":abc")
	m = vim.GetMode()
	fmt.Printf("COMMAND = %d %X\n", m, m)
	vim.Key("<esc>")
	vim.Key("<esc>")
	vim.Input("da")
	m = vim.GetMode()
	fmt.Printf("da = %d %X\n", m, m)
	vim.Key("<esc>")

	pos = vim.CursorGetPosition()
	fmt.Printf("Position: line = %d, col = %d\n", pos[0]-1, pos[1])

	vim.CursorSetPosition([2]int{2, 5})

	pos = vim.CursorGetPosition()
	fmt.Printf("Position: line = %d, col = %d\n", pos[0]-1, pos[1])

	vim.Execute("e!") // this throws away unsaved changes since the last save

	vim.Key("<esc>")
	vim.Input("gg")
	z := vim.CursorGetLine()
	fmt.Printf("line number = %d\n", z)

	vim.Input("G")
	z = vim.CursorGetLine()
	fmt.Printf("line number = %d\n", z)

	mod := vim.BufferGetModified(buf0)
	fmt.Printf("Buffer modified = %t\n", mod)
	vim.Input("gginorm [⌘] \x1b")
	mod = vim.BufferGetModified(buf0)
	fmt.Printf("Buffer modified = %t\n", mod)
	vim.Execute("w")
	mod = vim.BufferGetModified(buf0)
	fmt.Printf("Buffer modified = %t\n", mod)
	//vim.Key("<esc>")
	//vim.Input("\x1b")
	vim.Input("3lijon\x1b")
	z = vim.CursorGetLine()
	fmt.Printf("line number = %d\n", z)
	line := vim.BufferGetLine(buf0, 3)
	fmt.Printf("%s\n", line)

	vim.BufferSetLines(buf0, 0, 0, "Hello very young [\xe2\x8c\x98] [\u2318]lovers wherever you are!", 1)
	line = vim.BufferGetLine(buf0, 1)
	fmt.Printf("%s\n", line)
	bb := vim.BufferGetLine2(buf0, 1)
	fmt.Printf("% x\n", bb)
	ss = vim.BufferLinesS(buf0)
	fmt.Printf("%v\n", ss)
	pos = vim.CursorGetPosition()
	fmt.Printf("Position: line = %d, col = %d\n", pos[0]-1, pos[1])

	vim.Key("<esc>")
	vim.Execute("let length = strlen('Hello')")
	s := vim.Eval("length")
	fmt.Printf("length = %s\n", s)

	vim.Key("<esc>")
	//vim.Execute("source $VIMRUNTIME/defaults.vim")
	//vim.Execute("let sug = spellsuggest(expand('<cword>')")
	//vim.Execute("set spell")
	vim.Execute("set spell spelllang=/home/slzatz/vim_test/spell/en.utf-8.spl")
	//vim.Execute("set sps=/home/slzatz/vim_test/spell/en.utf-8.sug")
	vim.Execute("let g:sug = spellsuggest('tremendus', 5)")
	d := vim.Eval("dictionary?")
	//s = vim.Eval("spellsuggest('helllo', 5)")
	//vim.Execute("let sug = [1,2,3,4]") //this works
	s = vim.Eval("string(sug)")
	//d := vim.Eval("dict)")
	//s = vim.Eval("echo sug")
	fmt.Printf("sug = %v %d\n", s, len(s))
	fmt.Printf("dict = %v %d\n", d, len(d))
	vim.Execute("let word = expand('<cword>')")
	s = vim.Eval("word")
	fmt.Printf("word = %s\n", s)
	buf1 := vim.BufferNew(0)
	i = vim.BufferGetId(buf1)
	fmt.Printf("New buffer id = %d\n", i)

	buf_current := vim.BufferGetCurrent()
	i = vim.BufferGetId(buf_current)
	fmt.Printf("Current buffer id = %d\n", i)

	vim.BufferSetCurrent(buf1)
	buf_current = vim.BufferGetCurrent()
	i = vim.BufferGetId(buf_current)
	fmt.Printf("Current buffer id = %d\n", i)
	vim.BufferSetLinesBB(buf1, 0, -1, [][]byte{[]byte("Hello Hello Hello Hello Hello\x00"), []byte("Goodbye\xe2\x8c\x98\u2318\x00"), []byte("Peace\x00")}, 1)
	ss = vim.BufferLinesS(buf1)
	fmt.Printf("%v\n", ss)
	n = vim.BufferGetLineCount(buf1)
	fmt.Printf("Line Count = %d\n", n)
	//vim.BufferSetLinesBBB(buf1, 0, -1, [][]byte{[]byte("Hello"), []byte("Goodbye"), []byte("Peace")}, 1)
	vim.BufferSetLinesBBBB(buf1, [][]byte{[]byte("Hello Hello Hello Hello Hello"), []byte("Goodbye"), []byte("Peace")})
	ss = vim.BufferLinesS(buf1)
	fmt.Printf("%v\n", ss)
	n = vim.BufferGetLineCount(buf1)
	fmt.Printf("Line Count = %d\n", n)
	fmt.Println("**** Matching ***")
	zz := vim.BufferGetLine(buf0, 3)
	fmt.Printf("line text = %s\n", zz)
	vim.BufferSetCurrent(buf0)
	vim.Input2("3gg012l")
	pos = vim.CursorGetPosition()
	fmt.Printf("Position: line = %d, col = %d\n", pos[0], pos[1])
	pos = vim.SearchGetMatchingPair()
	fmt.Printf("Matching Position: line = %d, col = %d\n", pos[0], pos[1])
	//vim.Execute("changes")
	//s = vim.GetLastMessage2()
	//fmt.Printf("Last Message = %s\nlen = %d\n", s, len(s))
	vim.Execute("buffers")
	//vim.Execute("echomsg 'hello'") //works
	//vim.Execute("files")
	ss = vim.GetLastMessage2()
	fmt.Printf("Last Message = %v\nlen = %d\n", ss, len(ss))
	vim.Input2("ma")
	ss = vim.GetLastMessage2()
	fmt.Printf("Last Message = %v\nlen = %d\n", ss, len(ss))
	vim.Input2("jmb")
	vim.Execute("marks")
	ss = vim.GetLastMessage2()
	fmt.Printf("Last Message = %v\nlen = %d\n", ss, len(ss))
	fmt.Println("Done")

}
